### ISSUE TITLE
Wallet Bugs

### ISSUE THREAD

**Issue by flappys** [hippospace/aptos-wallet-adapter#19] opened 2022-09-02 06:09 UTC
1. If you close the martian/petra/spika wallet using the cross icon on the top most right side, UI doesn't capture that action and keep waiting. User rejected is only captured when user cancels from the cancel option giving below approve.
2. Click Aptos wallets opens both petra and spika. Same goes when you click spika
3. Spika doesn't allow sign message. Probably it has not implemented it.
4. On clicking Pontem, it logs in automatically without any pop up, even if the wallet is locked. Also it doesn't allow sign mesaage. The hello from account doesn't show account id.

I believe most of it will be wallets issues rather adapter issues.

**Comment by tom-hippo** [comment] 2022-09-08 07:36
Thank you for the feedback.
For q1, i think it will need the solution from the wallet extension side. We will report the situation to them to improve the UX.
For q2, it seems to be fixed in the latest version of Petra and Spika, please test it out.
q3: yes, Spika still haven't supported the sign message method. Will work with them.
q4: the issue is due to the missing disconnect function of Pontem. We have already reported the issue, looking forward to their updates.

**Closed** 2022-09-22 01:54 UTC
